import React, { useRef } from 'react';
import { Download, Printer, Share2, ShieldCheck, MapPin, Calendar, Building, User } from 'lucide-react';
import { passesAPI } from '../api/api';

/**
 * ============================================================================
 * PASS BADGE COMPONENT (Digital Visitor ID Badge)
 * ============================================================================
 * 
 * Beginner Guide for Trainees:
 * 1. Purpose:
 *    - Renders the official visual badge for any issued visitor pass.
 *    - Displays the visitor's photo, host info, gate, visit purpose, and dynamic QR Code.
 * 
 * 2. Actions:
 *    - `handlePrint()`: Triggers browser print (styled to fit on 1 single sheet).
 *    - `handleDownloadPDF()`: Streams the server-generated PDF badge from `/api/passes/:id/pdf`.
 *    - `handleCopyLink()`: Copies the public verification URL to the clipboard.
 * 
 * 3. Props:
 *    - `pass`: The Pass document object from MongoDB containing visitor, host, and appointment details.
 */
const PassBadge = ({ pass }) => {
  const badgeRef = useRef(null);

  if (!pass) return null;

  // Extract linked sub-documents safely with fallbacks
  const visitor = pass.visitor || {};
  const host = pass.host || {};
  const appointment = pass.appointment || {};

  // Action 1: Print Badge
  const handlePrint = () => {
    window.print();
  };

  // Action 2: Download PDF Badge generated by backend PDFKit
  const handleDownloadPDF = () => {
    const pdfUrl = passesAPI.getPdfUrl(pass.passCode || pass._id);
    window.open(pdfUrl, '_blank');
  };

  // Action 3: Copy shareable public link
  const handleCopyLink = () => {
    const publicUrl = `${window.location.origin}/pass/${pass.passCode}`;
    navigator.clipboard.writeText(publicUrl);
    alert('Public Pass Link copied to clipboard!\n' + publicUrl);
  };

  // Helper function to pick classy status colors
  const getStatusColor = (status) => {
    switch (status) {
      case 'Active': return '#059669';     // Green
      case 'CheckedIn': return '#2563eb';  // Blue
      case 'Completed': return '#475569';  // Gray
      case 'Expired': return '#dc2626';    // Red
      default: return '#d97706';           // Amber
    }
  };

  const formattedDate = pass.validFrom
    ? new Date(pass.validFrom).toLocaleDateString(undefined, {
        weekday: 'short',
        year: 'numeric',
        month: 'short',
        day: 'numeric',
      })
    : new Date().toLocaleDateString();

  return (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '1.25rem' }}>
      {/* Printable Badge Card Container */}
      <div ref={badgeRef} className="visitor-badge-card printable-badge">
        {/* Top Header Strip */}
        <div className="badge-header-strip">
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.4rem' }}>
            <ShieldCheck size={18} />
            <span style={{ fontSize: '0.95rem', fontWeight: 800, letterSpacing: '0.05em' }}>VISITOR PASS</span>
          </div>
          <p style={{ fontSize: '0.72rem', opacity: 0.9, marginTop: '2px' }}>TechCorp Solutions HQ</p>
        </div>

        {/* Visitor Photo Avatar */}
        <div className="badge-photo-wrapper">
          {visitor.photo ? (
            <img src={visitor.photo} alt={visitor.fullName} className="badge-avatar" />
          ) : (
            <div
              className="badge-avatar"
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                background: '#f1f5f9',
                color: '#2563eb',
                fontSize: '1.4rem',
                fontWeight: 700,
              }}
            >
              {visitor.fullName ? visitor.fullName.charAt(0) : 'V'}
            </div>
          )}
        </div>

        {/* Visitor Details */}
        <div style={{ padding: '0.75rem 1.25rem 0.5rem' }}>
          <h3 style={{ fontSize: '1.15rem', fontWeight: 700, color: '#0f172a' }}>{visitor.fullName || 'Guest Visitor'}</h3>
          <p style={{ fontSize: '0.8rem', color: '#64748b', fontWeight: 500 }}>
            {visitor.company || 'Self / Independent'}
          </p>

          <div
            style={{
              display: 'inline-block',
              background: '#f8fafc',
              border: '1px dashed #cbd5e1',
              borderRadius: '6px',
              padding: '0.2rem 0.65rem',
              fontSize: '0.8rem',
              fontWeight: 700,
              color: '#0f172a',
              marginTop: '0.4rem',
              letterSpacing: '0.04em',
            }}
          >
            PASS #{pass.passCode}
          </div>
        </div>

        {/* Divider Line */}
        <div style={{ height: '1px', background: '#e2e8f0', margin: '0.4rem 1.25rem' }} />

        {/* Appointment Metadata */}
        <div style={{ padding: '0 1.25rem', textAlign: 'left', fontSize: '0.78rem', color: '#334155' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', marginBottom: '0.3rem' }}>
            <User size={13} color="#2563eb" />
            <span><strong>Host:</strong> {host.name || 'Staff'} ({host.department || 'General'})</span>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', marginBottom: '0.3rem' }}>
            <Building size={13} color="#2563eb" />
            <span><strong>Purpose:</strong> {appointment.purpose || 'Official Visit'}</span>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', marginBottom: '0.3rem' }}>
            <Calendar size={13} color="#2563eb" />
            <span><strong>Date:</strong> {formattedDate} ({appointment.visitTime || '10:00 AM'})</span>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', marginBottom: '0.4rem' }}>
            <MapPin size={13} color="#2563eb" />
            <span><strong>Gate:</strong> {pass.gateNumber || 'Main Gate 1'}</span>
          </div>
        </div>

        {/* QR Code Card Box */}
        <div
          style={{
            background: '#ffffff',
            padding: '0.6rem',
            margin: '0.4rem 1.25rem',
            border: '1px solid #cbd5e1',
            borderRadius: '10px',
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
          }}
        >
          {pass.qrCode ? (
            <img
              src={pass.qrCode}
              alt={`QR code for pass ${pass.passCode}`}
              style={{ width: '120px', height: '120px', objectFit: 'contain' }}
            />
          ) : (
            <div style={{ width: '120px', height: '120px', background: '#f8fafc', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              QR Loading...
            </div>
          )}
        </div>

        {/* Badge Security Footer Text */}
        <p style={{ fontSize: '0.66rem', color: '#94a3b8', padding: '0 1rem 0.4rem' }}>
          Present this badge at security gates upon entry and exit.
        </p>

        {/* Live Status Bottom Strip */}
        <div
          style={{
            background: getStatusColor(pass.status),
            color: '#ffffff',
            padding: '0.35rem',
            fontSize: '0.75rem',
            fontWeight: 700,
            letterSpacing: '0.05em',
            textTransform: 'uppercase',
          }}
        >
          STATUS: {pass.status}
        </div>
      </div>

      {/* Action Buttons (Hidden when printing via CSS .no-print) */}
      <div className="no-print" style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap', justifyContent: 'center' }}>
        <button onClick={handleDownloadPDF} className="btn btn-primary btn-sm">
          <Download size={14} /> Download PDF Badge
        </button>
        <button onClick={handlePrint} className="btn btn-secondary btn-sm">
          <Printer size={14} /> Print Badge
        </button>
        <button onClick={handleCopyLink} className="btn btn-secondary btn-sm" title="Share public pass link">
          <Share2 size={14} /> Share Link
        </button>
      </div>
    </div>
  );
};

export default PassBadge;
